[package]
authors = ["Braden Steffaniak"]
categories = [
    "command-line-interface",
    "command-line-utilities",
    "visualization",
]
description = "Magnify your logs"
edition = "2021"
keywords = ["filter", "logging", "logs", "search"]
license = "MPL-2.0"
name = "magnilog"
readme = "README.md"
repository = "https://github.com/BSteffaniak/MagniLog"
version = "0.1.0"

[[bin]]
name              = "magnilog"
path              = "src/main.rs"
required-features = []

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
log = "0.4.22"
thiserror = "1.0.63"
tokio = { version = "1.39.3", features = [
    "fs",
    "io-util",
    "macros",
    "rt-multi-thread",
    "sync",
    "tracing",
] }
tokio-stream = "0.1.15"
tokio-util = "0.7.11"

[features]
fail-on-warnings = []
