name: Build and Test

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: ⚡ Cache cargo
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-magnilog-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Build MagniLog
              shell: bash
              run: |
                  cargo build \
                        --verbose \
                        --features=fail-on-warnings

            - name: Run MagniLog tests
              shell: bash
              run: |
                  cargo test \
                        --verbose \
                        --features=fail-on-warnings
